version: '3.8'

services:
  nessus:
    image: tenable/nessus:10.7.4-ubuntu
    container_name: nessus
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - ACTIVATION_CODE=${ACTIVATION_CODE}
    ports:
      - "8834:8834"
    volumes:
      - nessus_data:/opt/nessus
    restart: always
    networks:
      - local

  ms:
    container_name: metasploit
    image: metasploitframework/metasploit-framework:6.4.0
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    links:
      - db
    ports:
      - 4444:4444
    networks:
      - local

  db:
    container_name: postgres
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  nessus_data:
    driver: local
  pg_data:
    driver: local

networks:
  local:
